# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名称')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '规则配置',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('start_urls', models.TextField(verbose_name='起始url')),
                ('method', models.CharField(choices=[('get', 'GET'), ('post', 'POST')], default='get', max_length=6, verbose_name='请求方法')),
                ('headers', jsonfield.fields.JSONField(blank=True, default={'User_Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0'}, null=True, verbose_name='headers参数')),
                ('cookies', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='cookies参数')),
                ('form_data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='form-data参数')),
                ('proxy', models.BooleanField(verbose_name='启用代理')),
                ('dynamic', models.BooleanField(verbose_name='启用浏览器')),
                ('download_delay', models.PositiveSmallIntegerField(default=0, verbose_name='访问间隔(秒)')),
                ('concurrent_requests', models.PositiveSmallIntegerField(default=1, verbose_name='并发数量')),
                ('crawl_time', models.DateTimeField(blank=True, null=True, verbose_name='下次爬取时间')),
                ('frequency', models.IntegerField(default=86400, verbose_name='爬取频率(秒)')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.Rule', verbose_name='使用规则')),
            ],
            options={
                'verbose_name': '种子',
                'verbose_name_plural': '种子配置',
            },
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='字段名称')),
                ('type', models.CharField(choices=[('SelectorText', '文本选择器'), ('SelectorLink', '翻页选择器'), ('SelectorDetail', '详情页选择器'), ('SelectorHTML', 'html选择器'), ('SelectorElement', '元素集选择器'), ('SelectorImage', '图片选择器')], default='SelectorText', max_length=25, verbose_name='字段类型')),
                ('multiple', models.BooleanField(verbose_name='多元素')),
                ('method', models.CharField(choices=[('css', 'CSS'), ('xpath', 'XPATH')], default='css', max_length=5, verbose_name='定位方法')),
                ('selector', models.CharField(max_length=100, verbose_name='选择器')),
                ('regex', models.CharField(blank=True, max_length=100, null=True, verbose_name='正则过滤')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_selector', to='configs.Selector', verbose_name='父选择器')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_id', to='configs.Rule')),
            ],
            options={
                'verbose_name': '选择器',
                'verbose_name_plural': '选择器',
            },
        ),
    ]
