# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='crawl_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='下次爬取时间'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
    ]
